# coding: utf-8

"""
    Omnismith API

    API Documentation for Omnismith

    The version of the OpenAPI document: 1.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from omnismith_sdk.models.aggregate_entities_request_aggregations_inner import AggregateEntitiesRequestAggregationsInner
from omnismith_sdk.models.entity_filter import EntityFilter
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AggregateEntitiesRequest(BaseModel):
    """
    Which records to reduce, how to group them, and which reduces to compute per group.
    """ # noqa: E501
    filter_groups: Optional[List[List[EntityFilter]]] = Field(default=None, description="Narrows the records before grouping. Same grammar as the search endpoint: Filter groups: clauses inside a group are AND-ed, groups are OR-ed. `[]` applies no filter, `[[a, b]]` is `a AND b`, `[[a], [b, c]]` is `a OR (b AND c)`. Each clause is `{field, operator, value}` — see the `EntityFilter` schema for the shape. Unknown fields, operators that do not fit the field, malformed values, and reference paths into a template you cannot view are refused with 400/403.")
    group_by: Optional[List[StrictStr]] = Field(default=None, description="Attribute slugs or UUIDs to group by, at most 3. Lists, references, strings, numbers, booleans and dates can be keys; metrics, markdown, files and images cannot. Empty groups the whole filtered set into one row.")
    aggregations: List[AggregateEntitiesRequestAggregationsInner] = Field(description="Reduces computed for every group, reported back in this order. `count` takes no field; `sum` and `avg` need a number attribute; `min` and `max` accept number, date and datetime attributes.")
    limit: Optional[StrictInt] = Field(default=50, description="Maximum number of groups returned (1-100). The response says whether more groups exist.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["filter_groups", "group_by", "aggregations", "limit"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AggregateEntitiesRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in filter_groups (list of list)
        _items = []
        if self.filter_groups:
            for _item_filter_groups in self.filter_groups:
                if _item_filter_groups:
                    _items.append(
                         [_inner_item.to_dict() for _inner_item in _item_filter_groups if _inner_item is not None]
                    )
            _dict['filter_groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in aggregations (list)
        _items = []
        if self.aggregations:
            for _item_aggregations in self.aggregations:
                if _item_aggregations:
                    _items.append(_item_aggregations.to_dict())
            _dict['aggregations'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AggregateEntitiesRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "filter_groups": [
                    [EntityFilter.from_dict(_inner_item) for _inner_item in _item]
                    for _item in obj["filter_groups"]
                ] if obj.get("filter_groups") is not None else None,
            "group_by": obj.get("group_by"),
            "aggregations": [AggregateEntitiesRequestAggregationsInner.from_dict(_item) for _item in obj["aggregations"]] if obj.get("aggregations") is not None else None,
            "limit": obj.get("limit") if obj.get("limit") is not None else 50
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


