# coding: utf-8

"""
    Omnismith API

    API Documentation for Omnismith

    The version of the OpenAPI document: 1.0.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from omnismith_sdk.models.entity_rule_predicate import EntityRulePredicate
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EntityRuleResponse(BaseModel):
    """
    A template-scoped business rule: when every `when` condition holds (an empty list always holds), every `then` constraint must hold or the write is rejected with 422.
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="Rule UUID")
    template_id: Optional[UUID] = Field(default=None, description="UUID of the template the rule belongs to")
    name: Optional[StrictStr] = Field(default=None, description="Short name shown in the template editor")
    message: Optional[StrictStr] = Field(default=None, description="Text returned to the client when the rule is violated")
    is_enabled: Optional[StrictBool] = Field(default=None, description="Disabled rules are stored but not enforced")
    when: Optional[List[EntityRulePredicate]] = Field(default=None, description="Conditions that activate the rule; all must hold. Empty means the rule is unconditional.")
    then: Optional[List[EntityRulePredicate]] = Field(default=None, description="Constraints that must hold once the rule is active; at least one. Each failing constraint yields an `attributes.<slug>` error.")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "template_id", "name", "message", "is_enabled", "when", "then", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntityRuleResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in when (list)
        _items = []
        if self.when:
            for _item_when in self.when:
                if _item_when:
                    _items.append(_item_when.to_dict())
            _dict['when'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in then (list)
        _items = []
        if self.then:
            for _item_then in self.then:
                if _item_then:
                    _items.append(_item_then.to_dict())
            _dict['then'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntityRuleResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "template_id": obj.get("template_id"),
            "name": obj.get("name"),
            "message": obj.get("message"),
            "is_enabled": obj.get("is_enabled"),
            "when": [EntityRulePredicate.from_dict(_item) for _item in obj["when"]] if obj.get("when") is not None else None,
            "then": [EntityRulePredicate.from_dict(_item) for _item in obj["then"]] if obj.get("then") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


