# coding: utf-8

"""
    Omnismith API

    API Documentation for Omnismith

    The version of the OpenAPI document: 1.0.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from omnismith_sdk.models.entity_action_field import EntityActionField
from omnismith_sdk.models.entity_action_preset import EntityActionPreset
from omnismith_sdk.models.entity_rule_predicate import EntityRulePredicate
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EntityActionResponse(BaseModel):
    """
    A named, template-scoped operation on one record: a precondition that gates it, the fields the operator is asked for, and presets applied silently. Executing an action is one entity write that passes the template's rules like any other. A status transition is `precondition: [status eq draft]`, `presets: [status = confirmed]`.
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="Action UUID")
    template_id: Optional[UUID] = Field(default=None, description="UUID of the template the action belongs to")
    slug: Optional[StrictStr] = Field(default=None, description="Identifier used in URLs and by agents; unique per template")
    name: Optional[StrictStr] = Field(default=None, description="Label shown in menus and dialogs")
    description: Optional[StrictStr] = Field(default=None, description="What the action does, shown in the dialog")
    icon: Optional[StrictStr] = Field(default=None, description="Material icon name")
    is_enabled: Optional[StrictBool] = Field(default=None, description="Disabled actions are stored but neither listed for records nor executable")
    precondition: Optional[List[EntityRulePredicate]] = Field(default=None, description="Conditions on the record's current values that must all hold for the action to be available. Empty means always available.")
    fields: Optional[List[EntityActionField]] = Field(default=None, description="Values the operator is asked for, in dialog order")
    presets: Optional[List[EntityActionPreset]] = Field(default=None, description="Values written silently on execution")
    sort_order: Optional[StrictInt] = Field(default=None, description="Position among the template's actions, zero-based")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "template_id", "slug", "name", "description", "icon", "is_enabled", "precondition", "fields", "presets", "sort_order", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntityActionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in precondition (list)
        _items = []
        if self.precondition:
            for _item_precondition in self.precondition:
                if _item_precondition:
                    _items.append(_item_precondition.to_dict())
            _dict['precondition'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list)
        _items = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items.append(_item_fields.to_dict())
            _dict['fields'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in presets (list)
        _items = []
        if self.presets:
            for _item_presets in self.presets:
                if _item_presets:
                    _items.append(_item_presets.to_dict())
            _dict['presets'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if icon (nullable) is None
        # and model_fields_set contains the field
        if self.icon is None and "icon" in self.model_fields_set:
            _dict['icon'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntityActionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "template_id": obj.get("template_id"),
            "slug": obj.get("slug"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "icon": obj.get("icon"),
            "is_enabled": obj.get("is_enabled"),
            "precondition": [EntityRulePredicate.from_dict(_item) for _item in obj["precondition"]] if obj.get("precondition") is not None else None,
            "fields": [EntityActionField.from_dict(_item) for _item in obj["fields"]] if obj.get("fields") is not None else None,
            "presets": [EntityActionPreset.from_dict(_item) for _item in obj["presets"]] if obj.get("presets") is not None else None,
            "sort_order": obj.get("sort_order"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


