# coding: utf-8

"""
    Omnismith API

    API Documentation for Omnismith

    The version of the OpenAPI document: 1.0.15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from omnismith_sdk.models.entity_attributes_input_value_any_of_value import EntityAttributesInputValueAnyOfValue
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EntityAttributesInputValueAnyOf(BaseModel):
    """
    Backfill object: the same value plus the moment it was observed, for importing history.
    """ # noqa: E501
    value: EntityAttributesInputValueAnyOfValue
    updated_at: Optional[datetime] = Field(default=None, description="RFC 3339 timestamp with an explicit offset (`Z` or `±HH:MM`). Defaults to now when omitted.")
    __properties: ClassVar[List[str]] = ["value", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntityAttributesInputValueAnyOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of value
        if self.value:
            _dict['value'] = self.value.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntityAttributesInputValueAnyOf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "value": EntityAttributesInputValueAnyOfValue.from_dict(obj["value"]) if obj.get("value") is not None else None,
            "updated_at": obj.get("updated_at")
        })
        return _obj


