# coding: utf-8

"""
    Omnismith API

    API Documentation for Omnismith

    The version of the OpenAPI document: 1.0.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from omnismith_sdk.models.get_o_auth_authorize_info200_response_projects_inner import GetOAuthAuthorizeInfo200ResponseProjectsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetOAuthAuthorizeInfo200Response(BaseModel):
    """
    GetOAuthAuthorizeInfo200Response
    """ # noqa: E501
    client_id: Optional[StrictStr] = Field(default=None, description="OAuth client identifier")
    client_name: Optional[StrictStr] = Field(default=None, description="Human-readable client application name")
    redirect_uri: Optional[StrictStr] = Field(default=None, description="Validated redirection callback URI")
    scopes: Optional[List[StrictStr]] = Field(default=None, description="List of requested scopes")
    user_email: Optional[StrictStr] = Field(default=None, description="Email address of the currently authenticated user")
    active_project_id: Optional[StrictStr] = Field(default=None, description="Currently active project ID for the user session")
    projects: Optional[List[GetOAuthAuthorizeInfo200ResponseProjectsInner]] = Field(default=None, description="List of projects accessible by the authenticated user")
    state: Optional[StrictStr] = Field(default=None, description="Echoed client state parameter")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["client_id", "client_name", "redirect_uri", "scopes", "user_email", "active_project_id", "projects", "state"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetOAuthAuthorizeInfo200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in projects (list)
        _items = []
        if self.projects:
            for _item_projects in self.projects:
                if _item_projects:
                    _items.append(_item_projects.to_dict())
            _dict['projects'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if active_project_id (nullable) is None
        # and model_fields_set contains the field
        if self.active_project_id is None and "active_project_id" in self.model_fields_set:
            _dict['active_project_id'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetOAuthAuthorizeInfo200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "client_id": obj.get("client_id"),
            "client_name": obj.get("client_name"),
            "redirect_uri": obj.get("redirect_uri"),
            "scopes": obj.get("scopes"),
            "user_email": obj.get("user_email"),
            "active_project_id": obj.get("active_project_id"),
            "projects": [GetOAuthAuthorizeInfo200ResponseProjectsInner.from_dict(_item) for _item in obj["projects"]] if obj.get("projects") is not None else None,
            "state": obj.get("state")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


