# coding: utf-8

"""
    Omnismith API

    API Documentation for Omnismith

    The version of the OpenAPI document: 1.0.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from omnismith_sdk.models.import_entities200_response_affected_entities_inner_expected_attributes_inner import ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ImportEntities200ResponseAffectedEntitiesInner(BaseModel):
    """
    ImportEntities200ResponseAffectedEntitiesInner
    """ # noqa: E501
    entity_id: Optional[UUID] = None
    action: Optional[StrictStr] = None
    expected_attributes: Optional[List[ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInner]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["entity_id", "action", "expected_attributes"]

    @field_validator('action')
    def action_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['created', 'updated']):
            raise ValueError("must be one of enum values ('created', 'updated')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImportEntities200ResponseAffectedEntitiesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in expected_attributes (list)
        _items = []
        if self.expected_attributes:
            for _item_expected_attributes in self.expected_attributes:
                if _item_expected_attributes:
                    _items.append(_item_expected_attributes.to_dict())
            _dict['expected_attributes'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImportEntities200ResponseAffectedEntitiesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "entity_id": obj.get("entity_id"),
            "action": obj.get("action"),
            "expected_attributes": [ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInner.from_dict(_item) for _item in obj["expected_attributes"]] if obj.get("expected_attributes") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


