# coding: utf-8

"""
    Omnismith API

    API Documentation for Omnismith

    The version of the OpenAPI document: 1.0.16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from omnismith_sdk.models.preview_inbound_mapping200_response_items_inner import PreviewInboundMapping200ResponseItemsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PreviewInboundMapping200Response(BaseModel):
    """
    PreviewInboundMapping200Response
    """ # noqa: E501
    mode: StrictStr
    matched: StrictBool = Field(description="Whether the `match` conditions hold. When they do not, a real delivery is acknowledged and skipped.")
    skipped: Optional[StrictStr] = Field(description="`match` when the conditions do not hold, `no_items` when the `items` list is empty; null when records would be written.")
    items: List[PreviewInboundMapping200ResponseItemsInner]
    errors: Dict[str, List[StrictStr]] = Field(description="Every record error by field, `items[i].attributes.<slug>` => messages")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["mode", "matched", "skipped", "items", "errors"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['create', 'update', 'upsert']):
            raise ValueError("must be one of enum values ('create', 'update', 'upsert')")
        return value

    @field_validator('skipped')
    def skipped_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['match', 'no_items']):
            raise ValueError("must be one of enum values ('match', 'no_items')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PreviewInboundMapping200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if skipped (nullable) is None
        # and model_fields_set contains the field
        if self.skipped is None and "skipped" in self.model_fields_set:
            _dict['skipped'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PreviewInboundMapping200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mode": obj.get("mode"),
            "matched": obj.get("matched"),
            "skipped": obj.get("skipped"),
            "items": [PreviewInboundMapping200ResponseItemsInner.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "errors": obj.get("errors")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


