# coding: utf-8

"""
    Omnismith API

    API Documentation for Omnismith

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from omnismith_sdk.models.attribute_response import AttributeResponse
from omnismith_sdk.models.list_item_response import ListItemResponse
from omnismith_sdk.models.reference_config_response import ReferenceConfigResponse
from omnismith_sdk.models.template_response import TemplateResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProjectSchemaResponse(BaseModel):
    """
    Complete project schema including attributes, templates, list items, and reference configs
    """ # noqa: E501
    attributes: Optional[List[AttributeResponse]] = None
    templates: Optional[List[TemplateResponse]] = None
    list_items: Optional[List[ListItemResponse]] = None
    reference_configs: Optional[List[ReferenceConfigResponse]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["attributes", "templates", "list_items", "reference_configs"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectSchemaResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attributes (list)
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in templates (list)
        _items = []
        if self.templates:
            for _item_templates in self.templates:
                if _item_templates:
                    _items.append(_item_templates.to_dict())
            _dict['templates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in list_items (list)
        _items = []
        if self.list_items:
            for _item_list_items in self.list_items:
                if _item_list_items:
                    _items.append(_item_list_items.to_dict())
            _dict['list_items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in reference_configs (list)
        _items = []
        if self.reference_configs:
            for _item_reference_configs in self.reference_configs:
                if _item_reference_configs:
                    _items.append(_item_reference_configs.to_dict())
            _dict['reference_configs'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectSchemaResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attributes": [AttributeResponse.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None,
            "templates": [TemplateResponse.from_dict(_item) for _item in obj["templates"]] if obj.get("templates") is not None else None,
            "list_items": [ListItemResponse.from_dict(_item) for _item in obj["list_items"]] if obj.get("list_items") is not None else None,
            "reference_configs": [ReferenceConfigResponse.from_dict(_item) for _item in obj["reference_configs"]] if obj.get("reference_configs") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


