# coding: utf-8

"""
    Omnismith API

    API Documentation for Omnismith

    The version of the OpenAPI document: 1.0.11
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from omnismith_sdk.models.update_workspace_view_request_sort import UpdateWorkspaceViewRequestSort
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateWorkspaceViewRequest(BaseModel):
    """
    Payload for updating workspace view / pane configuration
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Updated display label for the view pane tab or header")
    filters: Optional[List[Dict[str, Any]]] = Field(default=None, description="Updated dynamic filtering rules applied to entities in this view")
    search_string: Optional[StrictStr] = Field(default=None, description="Updated search query string applied to entities in this view")
    search_mode: Optional[StrictStr] = Field(default=None, description="Updated search execution mode (keyword or semantic)")
    sort: Optional[UpdateWorkspaceViewRequestSort] = None
    display_mode: Optional[StrictStr] = Field(default=None, description="Updated presentation layout mode (table or grid)")
    displayed_columns: Optional[List[StrictStr]] = Field(default=None, description="Updated list of attribute slugs or UUIDs to display as columns")
    pane_order: Optional[StrictInt] = Field(default=None, description="Updated display sequence index within the workspace layout")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "filters", "search_string", "search_mode", "sort", "display_mode", "displayed_columns", "pane_order"]

    @field_validator('search_mode')
    def search_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['keyword', 'semantic']):
            raise ValueError("must be one of enum values ('keyword', 'semantic')")
        return value

    @field_validator('display_mode')
    def display_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['table', 'grid']):
            raise ValueError("must be one of enum values ('table', 'grid')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateWorkspaceViewRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sort
        if self.sort:
            _dict['sort'] = self.sort.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if filters (nullable) is None
        # and model_fields_set contains the field
        if self.filters is None and "filters" in self.model_fields_set:
            _dict['filters'] = None

        # set to None if search_string (nullable) is None
        # and model_fields_set contains the field
        if self.search_string is None and "search_string" in self.model_fields_set:
            _dict['search_string'] = None

        # set to None if search_mode (nullable) is None
        # and model_fields_set contains the field
        if self.search_mode is None and "search_mode" in self.model_fields_set:
            _dict['search_mode'] = None

        # set to None if sort (nullable) is None
        # and model_fields_set contains the field
        if self.sort is None and "sort" in self.model_fields_set:
            _dict['sort'] = None

        # set to None if display_mode (nullable) is None
        # and model_fields_set contains the field
        if self.display_mode is None and "display_mode" in self.model_fields_set:
            _dict['display_mode'] = None

        # set to None if displayed_columns (nullable) is None
        # and model_fields_set contains the field
        if self.displayed_columns is None and "displayed_columns" in self.model_fields_set:
            _dict['displayed_columns'] = None

        # set to None if pane_order (nullable) is None
        # and model_fields_set contains the field
        if self.pane_order is None and "pane_order" in self.model_fields_set:
            _dict['pane_order'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateWorkspaceViewRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "filters": obj.get("filters"),
            "search_string": obj.get("search_string"),
            "search_mode": obj.get("search_mode"),
            "sort": UpdateWorkspaceViewRequestSort.from_dict(obj["sort"]) if obj.get("sort") is not None else None,
            "display_mode": obj.get("display_mode"),
            "displayed_columns": obj.get("displayed_columns"),
            "pane_order": obj.get("pane_order")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


