# coding: utf-8

"""
    Omnismith API

    API Documentation for Omnismith

    The version of the OpenAPI document: 1.0.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from omnismith_sdk.models.patch_attribute_request_reference_config import PatchAttributeRequestReferenceConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateAttributeRequest(BaseModel):
    """
    Payload for full attribute update.
    """ # noqa: E501
    name: StrictStr = Field(description="Updated human-readable name of the attribute.")
    template_ids: Optional[List[UUID]] = Field(default=None, description="Complete list of template UUIDs associated with this attribute. Replaces current template associations while preserving restricted templates.")
    description: Optional[StrictStr] = Field(default=None, description="Updated description of the attribute.")
    reference_config: Optional[PatchAttributeRequestReferenceConfig] = None
    data_type: Optional[StrictInt] = Field(default=None, description="Target data type for lossless transition on Dimension (0) attributes: Number(1)->String(0), Boolean(2)->String(0), Date(4)<->Datetime(3), Date/Datetime->String(0), String(0)<->Markdown(7).")
    slug: Optional[StrictStr] = Field(default=None, description="Updated unique slug identifier within the project.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "template_ids", "description", "reference_config", "data_type", "slug"]

    @field_validator('data_type')
    def data_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1, 2, 3, 4, 5, 6, 7]):
            raise ValueError("must be one of enum values (0, 1, 2, 3, 4, 5, 6, 7)")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateAttributeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of reference_config
        if self.reference_config:
            _dict['reference_config'] = self.reference_config.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if reference_config (nullable) is None
        # and model_fields_set contains the field
        if self.reference_config is None and "reference_config" in self.model_fields_set:
            _dict['reference_config'] = None

        # set to None if data_type (nullable) is None
        # and model_fields_set contains the field
        if self.data_type is None and "data_type" in self.model_fields_set:
            _dict['data_type'] = None

        # set to None if slug (nullable) is None
        # and model_fields_set contains the field
        if self.slug is None and "slug" in self.model_fields_set:
            _dict['slug'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateAttributeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "template_ids": obj.get("template_ids"),
            "description": obj.get("description"),
            "reference_config": PatchAttributeRequestReferenceConfig.from_dict(obj["reference_config"]) if obj.get("reference_config") is not None else None,
            "data_type": obj.get("data_type"),
            "slug": obj.get("slug")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


