# coding: utf-8

"""
    Omnismith API

    API Documentation for Omnismith

    The version of the OpenAPI document: 1.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UsageResponse(BaseModel):
    """
    User resource usage statistics
    """ # noqa: E501
    attribute_count: Optional[StrictInt] = None
    template_count: Optional[StrictInt] = None
    entity_count: Optional[StrictInt] = None
    project_count: Optional[StrictInt] = None
    dashboard_count: Optional[StrictInt] = None
    disk_usage_bytes: Optional[StrictInt] = None
    monthly_metric_ingestions: Optional[StrictInt] = None
    monthly_dimension_updates: Optional[StrictInt] = None
    ai_credits_used: Optional[StrictInt] = None
    updated_at: Optional[datetime] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["attribute_count", "template_count", "entity_count", "project_count", "dashboard_count", "disk_usage_bytes", "monthly_metric_ingestions", "monthly_dimension_updates", "ai_credits_used", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsageResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsageResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attribute_count": obj.get("attribute_count"),
            "template_count": obj.get("template_count"),
            "entity_count": obj.get("entity_count"),
            "project_count": obj.get("project_count"),
            "dashboard_count": obj.get("dashboard_count"),
            "disk_usage_bytes": obj.get("disk_usage_bytes"),
            "monthly_metric_ingestions": obj.get("monthly_metric_ingestions"),
            "monthly_dimension_updates": obj.get("monthly_dimension_updates"),
            "ai_credits_used": obj.get("ai_credits_used"),
            "updated_at": obj.get("updated_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


